# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_detectUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 555)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(660, 8, 321, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.Setting_tab = QtWidgets.QWidget()
        self.Setting_tab.setObjectName("Setting_tab")
        self.frame = QtWidgets.QFrame(self.Setting_tab)
        self.frame.setGeometry(QtCore.QRect(1, 1, 314, 475))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 150, 291, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.writevideo_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.writevideo_checkBox.setCheckable(True)
        self.writevideo_checkBox.setChecked(False)
        self.writevideo_checkBox.setObjectName("writevideo_checkBox")
        self.verticalLayout_6.addWidget(self.writevideo_checkBox)
        self.writejpg_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.writejpg_checkBox.setCheckable(True)
        self.writejpg_checkBox.setChecked(False)
        self.writejpg_checkBox.setObjectName("writejpg_checkBox")
        self.verticalLayout_6.addWidget(self.writejpg_checkBox)
        self.bounding_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.bounding_checkBox.setObjectName("bounding_checkBox")
        self.verticalLayout_6.addWidget(self.bounding_checkBox)
        self.crop_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.crop_checkBox.setObjectName("crop_checkBox")
        self.verticalLayout_6.addWidget(self.crop_checkBox)
        self.display_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.display_checkBox.setObjectName("display_checkBox")
        self.verticalLayout_6.addWidget(self.display_checkBox)
        self.verbose_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.verbose_checkBox.setObjectName("verbose_checkBox")
        self.verticalLayout_6.addWidget(self.verbose_checkBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.detectA_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.detectA_radioButton.setObjectName("detectA_radioButton")
        self.horizontalLayout.addWidget(self.detectA_radioButton)
        self.detectB_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.detectB_radioButton.setObjectName("detectB_radioButton")
        self.horizontalLayout.addWidget(self.detectB_radioButton)
        self.detectC_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.detectC_radioButton.setObjectName("detectC_radioButton")
        self.horizontalLayout.addWidget(self.detectC_radioButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.imgscale_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.imgscale_comboBox.setObjectName("imgscale_comboBox")
        self.horizontalLayout_2.addWidget(self.imgscale_comboBox)
        self.imgsize_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.imgsize_label.setObjectName("imgsize_label")
        self.horizontalLayout_2.addWidget(self.imgsize_label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 360, 291, 111))
        self.groupBox.setObjectName("groupBox")
        self.detectionArea_Button = QtWidgets.QPushButton(self.groupBox)
        self.detectionArea_Button.setEnabled(False)
        self.detectionArea_Button.setGeometry(QtCore.QRect(170, 80, 109, 23))
        self.detectionArea_Button.setObjectName("detectionArea_Button")
        self.detectionTop_Edit = QtWidgets.QLineEdit(self.groupBox)
        self.detectionTop_Edit.setGeometry(QtCore.QRect(70, 20, 64, 20))
        self.detectionTop_Edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhEmailCharactersOnly)
        self.detectionTop_Edit.setObjectName("detectionTop_Edit")
        self.detectionBottom_Edit = QtWidgets.QLineEdit(self.groupBox)
        self.detectionBottom_Edit.setGeometry(QtCore.QRect(70, 80, 64, 20))
        self.detectionBottom_Edit.setObjectName("detectionBottom_Edit")
        self.detectionRight_Edit = QtWidgets.QLineEdit(self.groupBox)
        self.detectionRight_Edit.setGeometry(QtCore.QRect(110, 50, 64, 20))
        self.detectionRight_Edit.setObjectName("detectionRight_Edit")
        self.detectionLeft_Edit = QtWidgets.QLineEdit(self.groupBox)
        self.detectionLeft_Edit.setGeometry(QtCore.QRect(40, 50, 64, 20))
        self.detectionLeft_Edit.setObjectName("detectionLeft_Edit")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 31, 21))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(40, 80, 16, 21))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 31, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(180, 50, 31, 21))
        self.label_5.setObjectName("label_5")
        self.resetArea_Button = QtWidgets.QPushButton(self.groupBox)
        self.resetArea_Button.setGeometry(QtCore.QRect(196, 14, 80, 23))
        self.resetArea_Button.setObjectName("resetArea_Button")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 291, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outdirEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.outdirEdit.setReadOnly(True)
        self.outdirEdit.setObjectName("outdirEdit")
        self.horizontalLayout_4.addWidget(self.outdirEdit)
        self.outdirButton = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.outdirButton.setObjectName("outdirButton")
        self.horizontalLayout_4.addWidget(self.outdirButton)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 90, 301, 21))
        self.label.setObjectName("label")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 291, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.avi_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.avi_checkBox.setEnabled(True)
        self.avi_checkBox.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.avi_checkBox.setChecked(False)
        self.avi_checkBox.setObjectName("avi_checkBox")
        self.mov_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.mov_checkBox.setGeometry(QtCore.QRect(60, 20, 51, 16))
        self.mov_checkBox.setObjectName("mov_checkBox")
        self.mpg_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.mpg_checkBox.setGeometry(QtCore.QRect(110, 20, 51, 16))
        self.mpg_checkBox.setObjectName("mpg_checkBox")
        self.mp4_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.mp4_checkBox.setGeometry(QtCore.QRect(160, 20, 51, 16))
        self.mp4_checkBox.setObjectName("mp4_checkBox")
        self.wmv_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.wmv_checkBox.setGeometry(QtCore.QRect(210, 20, 51, 16))
        self.wmv_checkBox.setObjectName("wmv_checkBox")
        self.flv_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.flv_checkBox.setGeometry(QtCore.QRect(10, 50, 51, 16))
        self.flv_checkBox.setObjectName("flv_checkBox")
        self.mts_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.mts_checkBox.setGeometry(QtCore.QRect(60, 50, 51, 16))
        self.mts_checkBox.setObjectName("mts_checkBox")
        self.m2ts_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.m2ts_checkBox.setGeometry(QtCore.QRect(110, 50, 51, 16))
        self.m2ts_checkBox.setObjectName("m2ts_checkBox")
        self.tabWidget.addTab(self.Setting_tab, "")
        self.PlayList_tab = QtWidgets.QWidget()
        self.PlayList_tab.setObjectName("PlayList_tab")
        self.treeView = QtWidgets.QTreeView(self.PlayList_tab)
        self.treeView.setGeometry(QtCore.QRect(1, 1, 314, 475))
        self.treeView.setFrameShape(QtWidgets.QFrame.Box)
        self.treeView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.treeView.setObjectName("treeView")
        self.tabWidget.addTab(self.PlayList_tab, "")
        self.Log_tab = QtWidgets.QWidget()
        self.Log_tab.setObjectName("Log_tab")
        self.logEdit = QtWidgets.QTextEdit(self.Log_tab)
        self.logEdit.setGeometry(QtCore.QRect(1, 1, 314, 451))
        self.logEdit.setFrameShape(QtWidgets.QFrame.Box)
        self.logEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.logEdit.setReadOnly(True)
        self.logEdit.setObjectName("logEdit")
        self.clearlog_pushButton = QtWidgets.QPushButton(self.Log_tab)
        self.clearlog_pushButton.setGeometry(QtCore.QRect(235, 454, 75, 23))
        self.clearlog_pushButton.setObjectName("clearlog_pushButton")
        self.tabWidget.addTab(self.Log_tab, "")
        self.videoFrame = QtWidgets.QLabel(self.centralwidget)
        self.videoFrame.setGeometry(QtCore.QRect(10, 40, 640, 360))
        self.videoFrame.setMinimumSize(QtCore.QSize(640, 360))
        self.videoFrame.setMaximumSize(QtCore.QSize(640, 360))
        self.videoFrame.setAutoFillBackground(False)
        self.videoFrame.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.videoFrame.setText("")
        self.videoFrame.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.videoFrame.setObjectName("videoFrame")
        self.trackSlider = QtWidgets.QSlider(self.centralwidget)
        self.trackSlider.setGeometry(QtCore.QRect(10, 405, 640, 20))
        self.trackSlider.setMinimumSize(QtCore.QSize(640, 20))
        self.trackSlider.setMaximumSize(QtCore.QSize(640, 16777215))
        self.trackSlider.setOrientation(QtCore.Qt.Horizontal)
        self.trackSlider.setObjectName("trackSlider")
        self.fileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileEdit.setEnabled(True)
        self.fileEdit.setGeometry(QtCore.QRect(39, 8, 571, 20))
        self.fileEdit.setMinimumSize(QtCore.QSize(500, 0))
        self.fileEdit.setMaximumSize(QtCore.QSize(600, 16777215))
        self.fileEdit.setText("")
        self.fileEdit.setFrame(True)
        self.fileEdit.setReadOnly(True)
        self.fileEdit.setPlaceholderText("")
        self.fileEdit.setObjectName("fileEdit")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 430, 641, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.tracklabel = QtWidgets.QLabel(self.layoutWidget)
        self.tracklabel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tracklabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tracklabel.setObjectName("tracklabel")
        self.horizontalLayout_7.addWidget(self.tracklabel)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.trackalllabel = QtWidgets.QLabel(self.layoutWidget)
        self.trackalllabel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.trackalllabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trackalllabel.setObjectName("trackalllabel")
        self.horizontalLayout_7.addWidget(self.trackalllabel)
        self.previousvideoButton = QtWidgets.QPushButton(self.layoutWidget)
        self.previousvideoButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/leftarrow114.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousvideoButton.setIcon(icon)
        self.previousvideoButton.setObjectName("previousvideoButton")
        self.horizontalLayout_7.addWidget(self.previousvideoButton)
        self.playButton = QtWidgets.QPushButton(self.layoutWidget)
        self.playButton.setMinimumSize(QtCore.QSize(100, 60))
        self.playButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.playButton.setBaseSize(QtCore.QSize(0, 0))
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_7.addWidget(self.playButton)
        self.nextvideoButton = QtWidgets.QPushButton(self.layoutWidget)
        self.nextvideoButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/right arrow114.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextvideoButton.setIcon(icon1)
        self.nextvideoButton.setObjectName("nextvideoButton")
        self.horizontalLayout_7.addWidget(self.nextvideoButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.nextframeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.nextframeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/pause button4.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.nextframeButton.setIcon(icon2)
        self.nextframeButton.setObjectName("nextframeButton")
        self.horizontalLayout_7.addWidget(self.nextframeButton)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.speedSlider = QtWidgets.QSlider(self.layoutWidget)
        self.speedSlider.setMaximumSize(QtCore.QSize(50, 16777215))
        self.speedSlider.setProperty("value", 50)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName("speedSlider")
        self.horizontalLayout_7.addWidget(self.speedSlider)
        self.folderButton = QtWidgets.QToolButton(self.centralwidget)
        self.folderButton.setGeometry(QtCore.QRect(615, 8, 31, 21))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/folder265.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.folderButton.setIcon(icon3)
        self.folderButton.setObjectName("folderButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 31, 16))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionWebCam = QtWidgets.QAction(MainWindow)
        self.actionWebCam.setObjectName("actionWebCam")
        self.actionSave_Settings = QtWidgets.QAction(MainWindow)
        self.actionSave_Settings.setObjectName("actionSave_Settings")
        self.actionLoad_Settings = QtWidgets.QAction(MainWindow)
        self.actionLoad_Settings.setObjectName("actionLoad_Settings")
        self.actionAttach_CSV = QtWidgets.QAction(MainWindow)
        self.actionAttach_CSV.setObjectName("actionAttach_CSV")
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuFile.addAction(self.actionWebCam)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Settings)
        self.menuFile.addAction(self.actionSave_Settings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Animal Detect"))
        self.writevideo_checkBox.setText(_translate("MainWindow", "検知ビデオ(mov)書き出し"))
        self.writejpg_checkBox.setText(_translate("MainWindow", "検知画像(jpg)書き出し"))
        self.bounding_checkBox.setText(_translate("MainWindow", "検知エリア表示（ビデオ、画像書き出し時）"))
        self.crop_checkBox.setText(_translate("MainWindow", "検知範囲切り抜き（画像書き出し時）"))
        self.display_checkBox.setText(_translate("MainWindow", "モニター表示"))
        self.verbose_checkBox.setText(_translate("MainWindow", "ログ出力"))
        self.label_8.setText(_translate("MainWindow", "表示タイプ"))
        self.detectA_radioButton.setText(_translate("MainWindow", "A"))
        self.detectB_radioButton.setText(_translate("MainWindow", "B"))
        self.detectC_radioButton.setText(_translate("MainWindow", "C"))
        self.label_9.setText(_translate("MainWindow", "処理サイズ倍率"))
        self.imgsize_label.setText(_translate("MainWindow", "1280×720"))
        self.groupBox.setTitle(_translate("MainWindow", "検知範囲設定 (左,上 = 0,0)"))
        self.detectionArea_Button.setText(_translate("MainWindow", "マウスで矩形選択"))
        self.label_3.setText(_translate("MainWindow", "上"))
        self.label_6.setText(_translate("MainWindow", "下"))
        self.label_4.setText(_translate("MainWindow", "左"))
        self.label_5.setText(_translate("MainWindow", "右"))
        self.resetArea_Button.setText(_translate("MainWindow", "範囲リセット"))
        self.outdirButton.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "出力フォルダ"))
        self.groupBox_3.setTitle(_translate("MainWindow", "入力フォーマット"))
        self.avi_checkBox.setText(_translate("MainWindow", "avi"))
        self.mov_checkBox.setText(_translate("MainWindow", "mov"))
        self.mpg_checkBox.setText(_translate("MainWindow", "mpg"))
        self.mp4_checkBox.setText(_translate("MainWindow", "mp4"))
        self.wmv_checkBox.setText(_translate("MainWindow", "wmv"))
        self.flv_checkBox.setText(_translate("MainWindow", "flv"))
        self.mts_checkBox.setText(_translate("MainWindow", "mts"))
        self.m2ts_checkBox.setText(_translate("MainWindow", "m2ts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Setting_tab), _translate("MainWindow", "設定"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PlayList_tab), _translate("MainWindow", "再生リスト"))
        self.logEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS UI Gothic\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.clearlog_pushButton.setText(_translate("MainWindow", "クリア"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Log_tab), _translate("MainWindow", "ログ"))
        self.tracklabel.setText(_translate("MainWindow", "0:00:00"))
        self.label_10.setText(_translate("MainWindow", "/"))
        self.trackalllabel.setText(_translate("MainWindow", "0:00:00"))
        self.previousvideoButton.setToolTip(_translate("MainWindow", "前のビデオ"))
        self.playButton.setText(_translate("MainWindow", "START"))
        self.nextvideoButton.setToolTip(_translate("MainWindow", "次のビデオ"))
        self.nextframeButton.setToolTip(_translate("MainWindow", "コマ送り"))
        self.label_2.setText(_translate("MainWindow", "Speed"))
        self.folderButton.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "入力 "))
        self.menuFile.setTitle(_translate("MainWindow", "ファイル"))
        self.actionQuit.setText(_translate("MainWindow", "終了"))
        self.actionOpen_Folder.setText(_translate("MainWindow", "ビデオフォルダを開く..."))
        self.actionWebCam.setText(_translate("MainWindow", "カメラから入力..."))
        self.actionSave_Settings.setText(_translate("MainWindow", "設定を保存..."))
        self.actionSave_Settings.setIconText(_translate("MainWindow", "設定を保存..."))
        self.actionSave_Settings.setToolTip(_translate("MainWindow", "設定を保存..."))
        self.actionLoad_Settings.setText(_translate("MainWindow", "設定を読込み..."))
        self.actionAttach_CSV.setText(_translate("MainWindow", "CSVファイルを結合..."))

import video_detect_rc
