# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_detectUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(988, 555)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(660, 8, 321, 501))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Setting_tab = QtGui.QWidget()
        self.Setting_tab.setObjectName(_fromUtf8("Setting_tab"))
        self.frame = QtGui.QFrame(self.Setting_tab)
        self.frame.setGeometry(QtCore.QRect(1, 1, 314, 475))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayoutWidget = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 160, 291, 172))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.writevideo_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.writevideo_checkBox.setCheckable(True)
        self.writevideo_checkBox.setChecked(False)
        self.writevideo_checkBox.setObjectName(_fromUtf8("writevideo_checkBox"))
        self.verticalLayout_6.addWidget(self.writevideo_checkBox)
        self.writejpg_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.writejpg_checkBox.setCheckable(True)
        self.writejpg_checkBox.setChecked(False)
        self.writejpg_checkBox.setObjectName(_fromUtf8("writejpg_checkBox"))
        self.verticalLayout_6.addWidget(self.writejpg_checkBox)
        self.bounding_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.bounding_checkBox.setObjectName(_fromUtf8("bounding_checkBox"))
        self.verticalLayout_6.addWidget(self.bounding_checkBox)
        self.display_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.display_checkBox.setObjectName(_fromUtf8("display_checkBox"))
        self.verticalLayout_6.addWidget(self.display_checkBox)
        self.verbose_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.verbose_checkBox.setObjectName(_fromUtf8("verbose_checkBox"))
        self.verticalLayout_6.addWidget(self.verbose_checkBox)
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 350, 291, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.detectionArea_Button = QtGui.QPushButton(self.groupBox)
        self.detectionArea_Button.setEnabled(False)
        self.detectionArea_Button.setGeometry(QtCore.QRect(170, 80, 109, 23))
        self.detectionArea_Button.setObjectName(_fromUtf8("detectionArea_Button"))
        self.detectionTop_Edit = QtGui.QLineEdit(self.groupBox)
        self.detectionTop_Edit.setGeometry(QtCore.QRect(70, 20, 64, 20))
        self.detectionTop_Edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhEmailCharactersOnly)
        self.detectionTop_Edit.setObjectName(_fromUtf8("detectionTop_Edit"))
        self.detectionBottom_Edit = QtGui.QLineEdit(self.groupBox)
        self.detectionBottom_Edit.setGeometry(QtCore.QRect(70, 80, 64, 20))
        self.detectionBottom_Edit.setObjectName(_fromUtf8("detectionBottom_Edit"))
        self.detectionRight_Edit = QtGui.QLineEdit(self.groupBox)
        self.detectionRight_Edit.setGeometry(QtCore.QRect(110, 50, 64, 20))
        self.detectionRight_Edit.setObjectName(_fromUtf8("detectionRight_Edit"))
        self.detectionLeft_Edit = QtGui.QLineEdit(self.groupBox)
        self.detectionLeft_Edit.setGeometry(QtCore.QRect(40, 50, 64, 20))
        self.detectionLeft_Edit.setObjectName(_fromUtf8("detectionLeft_Edit"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 31, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(40, 80, 16, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 31, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(180, 50, 31, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 291, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.outdirEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.outdirEdit.setReadOnly(True)
        self.outdirEdit.setObjectName(_fromUtf8("outdirEdit"))
        self.horizontalLayout_4.addWidget(self.outdirEdit)
        self.outdirButton = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.outdirButton.setObjectName(_fromUtf8("outdirButton"))
        self.horizontalLayout_4.addWidget(self.outdirButton)
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 90, 301, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox_3 = QtGui.QGroupBox(self.frame)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 291, 80))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.avi_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.avi_checkBox.setEnabled(True)
        self.avi_checkBox.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.avi_checkBox.setChecked(False)
        self.avi_checkBox.setObjectName(_fromUtf8("avi_checkBox"))
        self.mov_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.mov_checkBox.setGeometry(QtCore.QRect(60, 20, 51, 16))
        self.mov_checkBox.setObjectName(_fromUtf8("mov_checkBox"))
        self.mpg_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.mpg_checkBox.setGeometry(QtCore.QRect(110, 20, 51, 16))
        self.mpg_checkBox.setObjectName(_fromUtf8("mpg_checkBox"))
        self.mp4_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.mp4_checkBox.setGeometry(QtCore.QRect(160, 20, 51, 16))
        self.mp4_checkBox.setObjectName(_fromUtf8("mp4_checkBox"))
        self.wmv_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.wmv_checkBox.setGeometry(QtCore.QRect(210, 20, 51, 16))
        self.wmv_checkBox.setObjectName(_fromUtf8("wmv_checkBox"))
        self.flv_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.flv_checkBox.setGeometry(QtCore.QRect(10, 50, 51, 16))
        self.flv_checkBox.setObjectName(_fromUtf8("flv_checkBox"))
        self.mts_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.mts_checkBox.setGeometry(QtCore.QRect(60, 50, 51, 16))
        self.mts_checkBox.setObjectName(_fromUtf8("mts_checkBox"))
        self.m2ts_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.m2ts_checkBox.setGeometry(QtCore.QRect(110, 50, 51, 16))
        self.m2ts_checkBox.setObjectName(_fromUtf8("m2ts_checkBox"))
        self.tabWidget.addTab(self.Setting_tab, _fromUtf8(""))
        self.PlayList_tab = QtGui.QWidget()
        self.PlayList_tab.setObjectName(_fromUtf8("PlayList_tab"))
        self.treeView = QtGui.QTreeView(self.PlayList_tab)
        self.treeView.setGeometry(QtCore.QRect(1, 1, 314, 475))
        self.treeView.setFrameShape(QtGui.QFrame.Box)
        self.treeView.setFrameShadow(QtGui.QFrame.Plain)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.tabWidget.addTab(self.PlayList_tab, _fromUtf8(""))
        self.Log_tab = QtGui.QWidget()
        self.Log_tab.setObjectName(_fromUtf8("Log_tab"))
        self.logEdit = QtGui.QTextEdit(self.Log_tab)
        self.logEdit.setGeometry(QtCore.QRect(1, 1, 314, 475))
        self.logEdit.setFrameShape(QtGui.QFrame.Box)
        self.logEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.logEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logEdit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.logEdit.setReadOnly(True)
        self.logEdit.setObjectName(_fromUtf8("logEdit"))
        self.tabWidget.addTab(self.Log_tab, _fromUtf8(""))
        self.videoFrame = QtGui.QLabel(self.centralwidget)
        self.videoFrame.setGeometry(QtCore.QRect(10, 40, 640, 360))
        self.videoFrame.setMinimumSize(QtCore.QSize(640, 360))
        self.videoFrame.setMaximumSize(QtCore.QSize(640, 360))
        self.videoFrame.setAutoFillBackground(False)
        self.videoFrame.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.videoFrame.setText(_fromUtf8(""))
        self.videoFrame.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.videoFrame.setObjectName(_fromUtf8("videoFrame"))
        self.trackSlider = QtGui.QSlider(self.centralwidget)
        self.trackSlider.setGeometry(QtCore.QRect(10, 405, 640, 20))
        self.trackSlider.setMinimumSize(QtCore.QSize(640, 20))
        self.trackSlider.setMaximumSize(QtCore.QSize(640, 16777215))
        self.trackSlider.setOrientation(QtCore.Qt.Horizontal)
        self.trackSlider.setObjectName(_fromUtf8("trackSlider"))
        self.fileEdit = QtGui.QLineEdit(self.centralwidget)
        self.fileEdit.setEnabled(True)
        self.fileEdit.setGeometry(QtCore.QRect(39, 8, 571, 20))
        self.fileEdit.setMinimumSize(QtCore.QSize(500, 0))
        self.fileEdit.setMaximumSize(QtCore.QSize(600, 16777215))
        self.fileEdit.setText(_fromUtf8(""))
        self.fileEdit.setFrame(True)
        self.fileEdit.setReadOnly(True)
        self.fileEdit.setPlaceholderText(_fromUtf8(""))
        self.fileEdit.setObjectName(_fromUtf8("fileEdit"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 430, 641, 71))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.tracklabel = QtGui.QLabel(self.layoutWidget)
        self.tracklabel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tracklabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tracklabel.setObjectName(_fromUtf8("tracklabel"))
        self.horizontalLayout_7.addWidget(self.tracklabel)
        self.previousvideoButton = QtGui.QPushButton(self.layoutWidget)
        self.previousvideoButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/leftarrow114.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousvideoButton.setIcon(icon)
        self.previousvideoButton.setObjectName(_fromUtf8("previousvideoButton"))
        self.horizontalLayout_7.addWidget(self.previousvideoButton)
        self.playButton = QtGui.QPushButton(self.layoutWidget)
        self.playButton.setMinimumSize(QtCore.QSize(100, 60))
        self.playButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.playButton.setBaseSize(QtCore.QSize(0, 0))
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.horizontalLayout_7.addWidget(self.playButton)
        self.nextvideoButton = QtGui.QPushButton(self.layoutWidget)
        self.nextvideoButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/right arrow114.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextvideoButton.setIcon(icon1)
        self.nextvideoButton.setObjectName(_fromUtf8("nextvideoButton"))
        self.horizontalLayout_7.addWidget(self.nextvideoButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.nextframeButton = QtGui.QPushButton(self.layoutWidget)
        self.nextframeButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/pause button4.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.nextframeButton.setIcon(icon2)
        self.nextframeButton.setObjectName(_fromUtf8("nextframeButton"))
        self.horizontalLayout_7.addWidget(self.nextframeButton)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.speedSlider = QtGui.QSlider(self.layoutWidget)
        self.speedSlider.setMaximumSize(QtCore.QSize(50, 16777215))
        self.speedSlider.setProperty("value", 50)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName(_fromUtf8("speedSlider"))
        self.horizontalLayout_7.addWidget(self.speedSlider)
        self.folderButton = QtGui.QToolButton(self.centralwidget)
        self.folderButton.setGeometry(QtCore.QRect(615, 8, 31, 21))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/folder265.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.folderButton.setIcon(icon3)
        self.folderButton.setObjectName(_fromUtf8("folderButton"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 31, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionOpen_Folder = QtGui.QAction(MainWindow)
        self.actionOpen_Folder.setObjectName(_fromUtf8("actionOpen_Folder"))
        self.actionWebCam = QtGui.QAction(MainWindow)
        self.actionWebCam.setObjectName(_fromUtf8("actionWebCam"))
        self.actionSave_Settings = QtGui.QAction(MainWindow)
        self.actionSave_Settings.setObjectName(_fromUtf8("actionSave_Settings"))
        self.actionLoad_Settings = QtGui.QAction(MainWindow)
        self.actionLoad_Settings.setObjectName(_fromUtf8("actionLoad_Settings"))
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuFile.addAction(self.actionWebCam)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Settings)
        self.menuFile.addAction(self.actionSave_Settings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Animal Detect", None))
        self.writevideo_checkBox.setText(_translate("MainWindow", "検知ビデオ(mov)書き出し", None))
        self.writejpg_checkBox.setText(_translate("MainWindow", "検知画像(jpg)書き出し", None))
        self.bounding_checkBox.setText(_translate("MainWindow", "検知エリア表示", None))
        self.display_checkBox.setText(_translate("MainWindow", "モニター表示", None))
        self.verbose_checkBox.setText(_translate("MainWindow", "ログ出力", None))
        self.groupBox.setTitle(_translate("MainWindow", "対象範囲設定 (左,上 = 0,0)", None))
        self.detectionArea_Button.setText(_translate("MainWindow", "マウスで選択", None))
        self.label_3.setText(_translate("MainWindow", "上", None))
        self.label_6.setText(_translate("MainWindow", "下", None))
        self.label_4.setText(_translate("MainWindow", "左", None))
        self.label_5.setText(_translate("MainWindow", "右", None))
        self.outdirButton.setText(_translate("MainWindow", "...", None))
        self.label.setText(_translate("MainWindow", "出力フォルダ", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "入力フォーマット", None))
        self.avi_checkBox.setText(_translate("MainWindow", "avi", None))
        self.mov_checkBox.setText(_translate("MainWindow", "mov", None))
        self.mpg_checkBox.setText(_translate("MainWindow", "mpg", None))
        self.mp4_checkBox.setText(_translate("MainWindow", "mp4", None))
        self.wmv_checkBox.setText(_translate("MainWindow", "wmv", None))
        self.flv_checkBox.setText(_translate("MainWindow", "flv", None))
        self.mts_checkBox.setText(_translate("MainWindow", "mts", None))
        self.m2ts_checkBox.setText(_translate("MainWindow", "m2ts", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Setting_tab), _translate("MainWindow", "設定", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PlayList_tab), _translate("MainWindow", "再生リスト", None))
        self.logEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS UI Gothic\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Log_tab), _translate("MainWindow", "ログ", None))
        self.tracklabel.setText(_translate("MainWindow", "0:00:00", None))
        self.previousvideoButton.setToolTip(_translate("MainWindow", "前のビデオ", None))
        self.playButton.setText(_translate("MainWindow", "START", None))
        self.nextvideoButton.setToolTip(_translate("MainWindow", "次のビデオ", None))
        self.nextframeButton.setToolTip(_translate("MainWindow", "コマ送り", None))
        self.label_2.setText(_translate("MainWindow", "Speed", None))
        self.folderButton.setText(_translate("MainWindow", "...", None))
        self.label_7.setText(_translate("MainWindow", "入力 ", None))
        self.menuFile.setTitle(_translate("MainWindow", "ファイル", None))
        self.actionQuit.setText(_translate("MainWindow", "終了", None))
        self.actionOpen_Folder.setText(_translate("MainWindow", "ビデオフォルダを開く...", None))
        self.actionWebCam.setText(_translate("MainWindow", "カメラから入力...", None))
        self.actionSave_Settings.setText(_translate("MainWindow", "設定を保存...", None))
        self.actionSave_Settings.setIconText(_translate("MainWindow", "設定を保存...", None))
        self.actionSave_Settings.setToolTip(_translate("MainWindow", "設定を保存...", None))
        self.actionLoad_Settings.setText(_translate("MainWindow", "設定を読込み...", None))

import video_detect_rc
